//
//  StyleKitName.m
//  ProjectName
//
//  Created by AuthorName on 2014-11-13.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKitName.h"


@implementation StyleKitName

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCanvas1
{
    //// Color Declarations
    NSColor* color0 = [NSColor colorWithCalibratedRed: 0.071 green: 0.071 blue: 0.071 alpha: 1];

    //// GlukitDroplet
    {
        //// Bezier 2 Drawing
        NSBezierPath* bezier2Path = NSBezierPath.bezierPath;
        [bezier2Path moveToPoint: NSMakePoint(362.99, 156)];
        [bezier2Path curveToPoint: NSMakePoint(363.91, 126.96) controlPoint1: NSMakePoint(364.62, 146.39) controlPoint2: NSMakePoint(364.5, 136.65)];
        [bezier2Path curveToPoint: NSMakePoint(338.42, 54.89) controlPoint1: NSMakePoint(362.04, 101.21) controlPoint2: NSMakePoint(354.47, 75.73)];
        [bezier2Path curveToPoint: NSMakePoint(271.96, 8.47) controlPoint1: NSMakePoint(321.5, 32.94) controlPoint2: NSMakePoint(297.72, 17.65)];
        [bezier2Path curveToPoint: NSMakePoint(230.44, 0) controlPoint1: NSMakePoint(258.83, 3.78) controlPoint2: NSMakePoint(244.44, 0.19)];
        [bezier2Path curveToPoint: NSMakePoint(107.16, 40.53) controlPoint1: NSMakePoint(175.34, 0) controlPoint2: NSMakePoint(139.76, 7.8)];
        [bezier2Path curveToPoint: NSMakePoint(73.12, 96.36) controlPoint1: NSMakePoint(91.62, 56.07) controlPoint2: NSMakePoint(79.48, 75.18)];
        [bezier2Path curveToPoint: NSMakePoint(68.77, 156) controlPoint1: NSMakePoint(67.21, 115.68) controlPoint2: NSMakePoint(66.73, 136.03)];
        [bezier2Path lineToPoint: NSMakePoint(362.99, 156)];
        [bezier2Path closePath];
        [bezier2Path setMiterLimit: 4];
        [color0 setFill];
        [bezier2Path fill];


        //// Bezier 4 Drawing
        NSBezierPath* bezier4Path = NSBezierPath.bezierPath;
        [bezier4Path moveToPoint: NSMakePoint(285.53, 431.26)];
        [bezier4Path lineToPoint: NSMakePoint(285.53, 431.26)];
        [bezier4Path curveToPoint: NSMakePoint(278.89, 392.47) controlPoint1: NSMakePoint(275.64, 420.64) controlPoint2: NSMakePoint(277.42, 405.72)];
        [bezier4Path curveToPoint: NSMakePoint(289.19, 344.74) controlPoint1: NSMakePoint(280.82, 376.31) controlPoint2: NSMakePoint(284.78, 360.38)];
        [bezier4Path curveToPoint: NSMakePoint(312.85, 275.28) controlPoint1: NSMakePoint(295.83, 321.19) controlPoint2: NSMakePoint(303.98, 298.07)];
        [bezier4Path curveToPoint: NSMakePoint(326.42, 243.57) controlPoint1: NSMakePoint(317.01, 264.6) controlPoint2: NSMakePoint(321.24, 253.81)];
        [bezier4Path curveToPoint: NSMakePoint(361.11, 167.31) controlPoint1: NSMakePoint(340.68, 219.45) controlPoint2: NSMakePoint(351.73, 193.67)];
        [bezier4Path lineToPoint: NSMakePoint(361.06, 167.23)];
        [bezier4Path lineToPoint: NSMakePoint(361.04, 167.28)];
        [bezier4Path lineToPoint: NSMakePoint(360.93, 166.87)];
        [bezier4Path curveToPoint: NSMakePoint(360.89, 166.73) controlPoint1: NSMakePoint(360.88, 166.79) controlPoint2: NSMakePoint(360.89, 166.83)];
        [bezier4Path curveToPoint: NSMakePoint(360.36, 165.8) controlPoint1: NSMakePoint(360.56, 166.11) controlPoint2: NSMakePoint(360.73, 166.42)];
        [bezier4Path curveToPoint: NSMakePoint(355.09, 162.01) controlPoint1: NSMakePoint(359.16, 164.08) controlPoint2: NSMakePoint(356.96, 162.81)];
        [bezier4Path curveToPoint: NSMakePoint(337.14, 158.52) controlPoint1: NSMakePoint(349.38, 159.72) controlPoint2: NSMakePoint(343.29, 158.69)];
        [bezier4Path curveToPoint: NSMakePoint(320.3, 161.66) controlPoint1: NSMakePoint(331.42, 158.89) controlPoint2: NSMakePoint(325.67, 159.5)];
        [bezier4Path curveToPoint: NSMakePoint(313.34, 168.24) controlPoint1: NSMakePoint(317.42, 162.82) controlPoint2: NSMakePoint(313.61, 164.73)];
        [bezier4Path curveToPoint: NSMakePoint(308.02, 162.38) controlPoint1: NSMakePoint(313.14, 165.33) controlPoint2: NSMakePoint(310.41, 163.55)];
        [bezier4Path curveToPoint: NSMakePoint(290.14, 158.56) controlPoint1: NSMakePoint(302.49, 159.68) controlPoint2: NSMakePoint(296.19, 158.95)];
        [bezier4Path curveToPoint: NSMakePoint(273.89, 161.66) controlPoint1: NSMakePoint(284.62, 158.92) controlPoint2: NSMakePoint(279.06, 159.58)];
        [bezier4Path curveToPoint: NSMakePoint(266.93, 168.24) controlPoint1: NSMakePoint(271.01, 162.82) controlPoint2: NSMakePoint(267.2, 164.73)];
        [bezier4Path curveToPoint: NSMakePoint(263.06, 163.17) controlPoint1: NSMakePoint(266.77, 165.9) controlPoint2: NSMakePoint(264.96, 164.31)];
        [bezier4Path curveToPoint: NSMakePoint(244.67, 158.62) controlPoint1: NSMakePoint(257.59, 159.88) controlPoint2: NSMakePoint(250.88, 159.13)];
        [bezier4Path curveToPoint: NSMakePoint(229.36, 161.66) controlPoint1: NSMakePoint(239.48, 158.96) controlPoint2: NSMakePoint(234.22, 159.71)];
        [bezier4Path curveToPoint: NSMakePoint(222.4, 168.24) controlPoint1: NSMakePoint(226.48, 162.82) controlPoint2: NSMakePoint(222.67, 164.73)];
        [bezier4Path curveToPoint: NSMakePoint(218.52, 163.17) controlPoint1: NSMakePoint(222.24, 165.9) controlPoint2: NSMakePoint(220.43, 164.31)];
        [bezier4Path curveToPoint: NSMakePoint(200.72, 158.66) controlPoint1: NSMakePoint(213.23, 159.98) controlPoint2: NSMakePoint(206.74, 159.19)];
        [bezier4Path curveToPoint: NSMakePoint(185.99, 161.66) controlPoint1: NSMakePoint(195.73, 158.98) controlPoint2: NSMakePoint(190.65, 159.79)];
        [bezier4Path curveToPoint: NSMakePoint(179.04, 168.24) controlPoint1: NSMakePoint(183.11, 162.82) controlPoint2: NSMakePoint(179.3, 164.73)];
        [bezier4Path curveToPoint: NSMakePoint(173.71, 162.38) controlPoint1: NSMakePoint(178.84, 165.33) controlPoint2: NSMakePoint(176.11, 163.55)];
        [bezier4Path curveToPoint: NSMakePoint(155.89, 158.56) controlPoint1: NSMakePoint(168.21, 159.69) controlPoint2: NSMakePoint(161.93, 158.96)];
        [bezier4Path curveToPoint: NSMakePoint(139.71, 161.66) controlPoint1: NSMakePoint(150.4, 158.92) controlPoint2: NSMakePoint(144.86, 159.59)];
        [bezier4Path curveToPoint: NSMakePoint(132.75, 168.24) controlPoint1: NSMakePoint(136.83, 162.82) controlPoint2: NSMakePoint(133.02, 164.73)];
        [bezier4Path curveToPoint: NSMakePoint(128.87, 163.17) controlPoint1: NSMakePoint(132.59, 165.9) controlPoint2: NSMakePoint(130.78, 164.31)];
        [bezier4Path curveToPoint: NSMakePoint(111.3, 158.67) controlPoint1: NSMakePoint(123.65, 160.02) controlPoint2: NSMakePoint(117.25, 159.21)];
        [bezier4Path curveToPoint: NSMakePoint(99.46, 160.69) controlPoint1: NSMakePoint(107.31, 159.03) controlPoint2: NSMakePoint(103.3, 159.47)];
        [bezier4Path curveToPoint: NSMakePoint(93.59, 163.17) controlPoint1: NSMakePoint(97.18, 161.37) controlPoint2: NSMakePoint(95.58, 162.03)];
        [bezier4Path curveToPoint: NSMakePoint(90.02, 166.75) controlPoint1: NSMakePoint(92.16, 163.98) controlPoint2: NSMakePoint(90.67, 165.2)];
        [bezier4Path curveToPoint: NSMakePoint(89.71, 168.24) controlPoint1: NSMakePoint(89.73, 167.44) controlPoint2: NSMakePoint(89.75, 167.63)];
        [bezier4Path lineToPoint: NSMakePoint(89.68, 167.74)];
        [bezier4Path curveToPoint: NSMakePoint(89.4, 166.75) controlPoint1: NSMakePoint(89.58, 167.41) controlPoint2: NSMakePoint(89.53, 167.07)];
        [bezier4Path curveToPoint: NSMakePoint(83.59, 162.01) controlPoint1: NSMakePoint(88.47, 164.51) controlPoint2: NSMakePoint(85.7, 162.9)];
        [bezier4Path curveToPoint: NSMakePoint(81.71, 161.28) controlPoint1: NSMakePoint(82.97, 161.77) controlPoint2: NSMakePoint(82.35, 161.49)];
        [bezier4Path curveToPoint: NSMakePoint(77.85, 160.11) controlPoint1: NSMakePoint(80.43, 160.86) controlPoint2: NSMakePoint(79.15, 160.44)];
        [bezier4Path curveToPoint: NSMakePoint(75.48, 159.58) controlPoint1: NSMakePoint(77.06, 159.93) controlPoint2: NSMakePoint(76.28, 159.72)];
        [bezier4Path curveToPoint: NSMakePoint(70.25, 158.85) controlPoint1: NSMakePoint(73.75, 159.26) controlPoint2: NSMakePoint(72.01, 159)];
        [bezier4Path curveToPoint: NSMakePoint(95.04, 232.03) controlPoint1: NSMakePoint(73.84, 184.45) controlPoint2: NSMakePoint(82.45, 209.45)];
        [bezier4Path lineToPoint: NSMakePoint(104.23, 248.4)];
        [bezier4Path curveToPoint: NSMakePoint(285.53, 431.26) controlPoint1: NSMakePoint(152.58, 320.21) controlPoint2: NSMakePoint(217.71, 378.34)];
        [bezier4Path lineToPoint: NSMakePoint(285.53, 431.26)];
        [bezier4Path lineToPoint: NSMakePoint(285.53, 431.26)];
        [bezier4Path lineToPoint: NSMakePoint(285.53, 431.26)];
        [bezier4Path lineToPoint: NSMakePoint(285.53, 431.26)];
        [bezier4Path lineToPoint: NSMakePoint(285.53, 431.26)];
        [bezier4Path lineToPoint: NSMakePoint(285.53, 431.26)];
        [bezier4Path lineToPoint: NSMakePoint(285.53, 431.26)];
        [bezier4Path lineToPoint: NSMakePoint(285.53, 431.26)];
        [bezier4Path closePath];
        [bezier4Path setMiterLimit: 4];
        [color0 setFill];
        [bezier4Path fill];
    }
}

@end
